### ISSUE TITLE
Add a language switching toggle

### ISSUE THREAD

**Issue by shanejann** [HandshakeAlliance/HNScan#220]
Extra credit: we COULD try to get our translations for our site auto generated to other languages. Of course, that comes with a risk, but it's 100x better than paying someone to do it. Doing this would allow us to test the language switch toggle more efficiently

see the docs for i18next and locize.com

**Comment by shanejann** [comment]
consider following this approach https://ethereum.org (but maybe JUST show the language)

**Comment by kilpatty** [comment]
So here's an approach I somewhat like. 

- We auto generate most of the language files. 
- When someone goes to a version of the site that is not English, and not audited, we show a disclaimer at the bottom. Something along the lines of `Something not translated correctly? Open up an issue here to help out` and link to Github. 
- Open up a meta issue with each language that is auto generated. Look for contributors to "audit" the translation and make any improvements needed.

**Comment by shanejann** [comment]
100% LOVE IT

**Comment by kilpatty** [comment]
Note to self, let’s add this to ucl

**Comment by shanejann** [comment]
To that point, we should also see about making the components be able to translate keys as well. Though that sounds like a toughie
