### ISSUE TITLE
Weird UI bug on Outputs

### ISSUE THREAD

**Issue by kilpatty** [HandshakeAlliance/HNScan#24]
<img width="544" alt="screen shot 2019-01-09 at 4 44 43 pm" src="https://user-images.githubusercontent.com/9666345/50934349-fcddf800-142d-11e9-87fa-aff4e5e41a28.png">

https://HNScan.com/address/hs1qtjr4ulexeu5gj7xnxvkfl9hljfh8yc5fnns8ts for relevant view

**Comment by shanejann** [comment]
This'll be fixed in this PR https://github.com/HandshakeAlliance/HNScan/pull/28

**Comment by kilpatty** [comment]
Good work @shanejann closing
