### ISSUE TITLE
Dark Theme - Make Body Dark

### ISSUE THREAD

**Issue by kilpatty** [HandshakeAlliance/HNScan#81]
Right now on light mode if the content of a page is not 100% then it's fine because the background color of the body is white. With dark mode, we show white if a screen is too small, we should make sure we are changing the background color of the body as well.

**Comment by kilpatty** [comment]
https://kevinchen.co/blog/support-macos-mojave-dark-mode-on-websites/

**Comment by shanejann** [comment]
The body (or in this case, html) now matches the background color of the content. Confirmed on both Chrome and Safari
