### ISSUE TITLE
Adding HNS Community to Footer?

### ISSUE THREAD

**Issue by smcki012** [HandshakeAlliance/HNScan#83]
Could we get this added to `foot.pug` @kilpatty? This will aid in backlinks for getting new community members into the Discourse channel as this explorer will be heavily traffic'd.

```
.columnItem
              a(class="columnLink" href="https://handshake.community target="_blank" rel="noopener noreferrer") Community
```

**Comment by kilpatty** [comment]
Paging @JGeiser9

**Comment by JGeiser9** [comment]
to the rescue..

**Comment by JGeiser9** [comment]
Added with commit f243f38c88f0d9ea1242e39105b8743ac8a42d17 deploying shortly
