### ISSUE TITLE
Address Error

### ISSUE THREAD

**Issue by JGeiser9** [HandshakeAlliance/HNScan#94]
When attempting to visit:
http://localhost:7000/address/ts1qg2schj9h0e3xr83jk0evy3h8m4wr0uk9qtdtzc

It returns what it should to the user, however there is a 500 internal server error log:

{ Error: Invalid bech32 string.
    at NomenclateClient.request (/Users/jakegeiser/HandshakeAlliance/HNScan/node_modules/nomenclate-js/node_modules/bcurl/lib/client.js:213:19)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'undefined', code: undefined }
{ TypeError: Cannot read property 'total_txs' of undefined
    at addressHandler (/Users/jakegeiser/HandshakeAlliance/HNScan/src/handlers/address.js:19:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  stack:
   'TypeError: Cannot read property \'total_txs\' of undefined\n    at addressHandler (/Users/jakegeiser/HandshakeAlliance/HNScan/src/handlers/address.js:19:37)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  message: 'Cannot read property \'total_txs\' of undefined',
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  isDeveloperError: true }

**Comment by shanejann** [comment]
Going to this page, I'm not seeing this error anymore...Perhaps I'll close this issue until it pops up again?

**Comment by JGeiser9** [comment]
Currently, clicking on this miner address on the blocks page (https://hnscan.com/blocks) is producing a 404. On our new version a 500 internal error is still being produced. Can you guys replicate as well? @shanejann @kilpatty

**Comment by kilpatty** [comment]
Yeah. Two thoughts of what this could be: 

1. Something is breaking once we hit a certain number of transactions per address preventing us from querying it. 
2. Something is breaking if an address has a transaction removed due to a reorg.

Both of these are results of the backend plugin breaking so I'm going to move this over to there.
